### ISSUE TITLE
Add RGB and rainbow 

### ISSUE THREAD

**Issue by tiotrom** [drunckj/gnome-shell-extension-asus-rgb#1]
rogauracore rainbow and 
single_static
   single_breathing
   single_colorcycle
   multi_static
   multi_breathing

Should be added. Thanks a lot for this btw.

**Comment by drunckj** [comment]
Yes I'll be adding those and creating a gui window for selecting any color from the rgb color range.

**Comment by tiotrom** [comment]
So wonderful. Thank you!
